<a href="https://colab.research.google.com/github/DRes16/challenge-alura-2/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
datos.head ()

                       {
"nbformat": 4        NaN
"nbformat_minor": 0  NaN
"metadata": {        NaN
  "colab": {         NaN
    "provenance": [] NaN

In [ ]:
datos = pd.read_csv('TelecomX_Data.json')

In [ ]:
datos_ipynb = pd.read_csv('TelecomX_LATAM.ipynb')

In [ ]:
# prompt: datos.head()

import pandas as pd
# Assuming TelecomX_Data.json is a CSV file and not a JSON file based on your read_csv attempt
# If it's actually a JSON file, you should use pd.read_json instead.
# Let's assume it's a CSV file for now.

# The previous lines already loaded and displayed the head of 'datos'.
# If you need to display it again:
# datos.head()

# It seems like you are trying to read an ipynb file as a CSV.
# An ipynb file is a notebook file and cannot be directly read as a CSV.
# If you intended to read data *from* the notebook, you would need to
# parse the notebook content, which is complex.
# If TelecomX_LATAM.ipynb is meant to be another CSV file, then correct the extension.

# Assuming you meant to read another CSV file named TelecomX_LATAM.csv
# If 'TelecomX_LATAM.ipynb' is indeed a CSV and named incorrectly, use:
# datos_latam = pd.read_csv('TelecomX_LATAM.ipynb') # Use this if it's a CSV with .ipynb extension

# If you meant to read a CSV named TelecomX_LATAM.csv, use:
# datos_latam = pd.read_csv('TelecomX_LATAM.csv')

# As the original code tried to read 'TelecomX_LATAM.ipynb' as a CSV,
# and that's likely incorrect unless it's a CSV with a wrong extension,
# I will keep the original line but add a comment about the potential issue.

# datos_ipynb = pd.read_csv('TelecomX_LATAM.ipynb') # Note: Reading an .ipynb as CSV is usually incorrect

# Let's re-display the head of the first dataframe as the prompt asked for `datos.head()`
print("Head of the 'datos' DataFrame:")
datos.head()

Head of the 'datos' DataFrame:

Empty DataFrame
Columns: [[{"customerID":"0002-ORFBO", Churn:"No", customer:{"gender":"Female", SeniorCitizen:0, Partner:"Yes", Dependents:"Yes", tenure:9}, phone:{"PhoneService":"Yes", MultipleLines:"No"}, internet:{"InternetService":"DSL", OnlineSecurity:"No", OnlineBackup:"Yes", DeviceProtection:"No", TechSupport:"Yes", StreamingTV:"Yes", StreamingMovies:"No"}, account:{"Contract":"One year", PaperlessBilling:"Yes", PaymentMethod:"Mailed check", Charges:{"Monthly":65.6, Total:"593.3"}}}, {"customerID":"0003-MKNFE", Churn:"No".1, customer:{"gender":"Male", SeniorCitizen:0.1, Partner:"No", Dependents:"No", tenure:9}.1, phone:{"PhoneService":"Yes".1, MultipleLines:"Yes"}, internet:{"InternetService":"DSL".1, OnlineSecurity:"No".1, OnlineBackup:"No", DeviceProtection:"No".1, TechSupport:"No", StreamingTV:"No", StreamingMovies:"Yes"}, account:{"Contract":"Month-to-month", PaperlessBilling:"No", PaymentMethod:"Mailed check".1, Charges:{"Monthly":59.9, Total:"542.4"}}}, {"customerID":"0004-TLHLJ", Churn:"Yes", customer:{"gender":"Male".1, SeniorCitizen:0.2, Partner:"No".1, Dependents:"No".1, tenure:4}, phone:{"PhoneService":"Yes".2, MultipleLines:"No"}.1, internet:{"InternetService":"Fiber optic", OnlineSecurity:"No".2, OnlineBackup:"No".1, DeviceProtection:"Yes", TechSupport:"No".1, StreamingTV:"No".1, StreamingMovies:"No"}.1, account:{"Contract":"Month-to-month".1, PaperlessBilling:"Yes".1, PaymentMethod:"Electronic check", Charges:{"Monthly":73.9, Total:"280.85"}}}, {"customerID":"0011-IGKFF", Churn:"Yes".1, customer:{"gender":"Male".2, SeniorCitizen:1, Partner:"Yes".1, Dependents:"No".2, tenure:13}, phone:{"PhoneService":"Yes".3, MultipleLines:"No"}.2, internet:{"InternetService":"Fiber optic".1, OnlineSecurity:"No".3, OnlineBackup:"Yes".1, DeviceProtection:"Yes".1, TechSupport:"No".2, StreamingTV:"Yes".1, StreamingMovies:"Yes"}.1, account:{"Contract":"Month-to-month".2, PaperlessBilling:"Yes".2, PaymentMethod:"Electronic check".1, Charges:{"Monthly":98.0, Total:"1237.85"}}}, {"customerID":"0013-EXCHZ", Churn:"Yes".2, customer:{"gender":"Female".1, SeniorCitizen:1.1, Partner:"Yes".2, Dependents:"No".3, tenure:3}, phone:{"PhoneService":"Yes".4, MultipleLines:"No"}.3, internet:{"InternetService":"Fiber optic".2, OnlineSecurity:"No".4, OnlineBackup:"No".2, DeviceProtection:"No".2, TechSupport:"Yes".1, StreamingTV:"Yes".2, StreamingMovies:"No"}.2, ...]
Index: []

[0 rows x 152607 columns]

In [ ]:
json_data.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7267 non-null   object
 1   Churn       7267 non-null   object
 2   customer    7267 non-null   object
 3   phone       7267 non-null   object
 4   internet    7267 non-null   object
 5   account     7267 non-null   object
dtypes: object(6)
memory usage: 340.8+ KB

# Nueva sección

In [ ]:
json_data.dtypes

customerID    object
Churn         object
customer      object
phone         object
internet      object
account       object
dtype: object

In [ ]:
import pandas
pandas.options.display.max_info_columns

100

In [ ]:
pd.unique(json_data['customer'])

TypeError: unhashable type: 'dict'

In [ ]:
pandas.Series.dt.normalize( json_data['customer'])

AttributeError: 'Series' object has no attribute '_delegate_method'

# Task
Convert the JSON data from "TelecomX_Data.json" to CSV format.

## Load json data

### Subtask:
Read the `TelecomX_Data.json` file using `pd.read_json`.

**Reasoning**:
The previous attempts to read the data as CSV failed because the file is in JSON format. The subtask requires reading the JSON file using `pd.read_json`.

In [ ]:
json_data = pd.read_json('TelecomX_Data.json')

**Reasoning**:
The subtask is to read the JSON file into a DataFrame, which was accomplished in the previous step. The next step is to verify the data was loaded correctly by displaying the first few rows.

In [ ]:
json_data.head()

In [ ]:
# prompt: Mediante el marco de datos json_data: gender

import pandas as pd
# Normalize the 'customer' column which contains nested JSON data
customer_df = pd.json_normalize(json_data['customer'])
# Display the first 5 rows of the normalized customer data
customer_df.head()

## Normalize nested data

### Subtask:
The JSON data appears to have nested structures. I will use `pd.json_normalize` to flatten the nested data into a DataFrame.

**Reasoning**:
Flatten the nested JSON data using `pd.json_normalize` and display the head of the resulting DataFrame to verify the structure.

In [ ]:
df_normalized = pd.json_normalize(json_data.to_dict(orient='records'))
display(df_normalized.head())

## Save as csv

### Subtask:
Save the normalized DataFrame to a new CSV file.

**Reasoning**:
Save the normalized DataFrame to a CSV file without the index.

In [ ]:
df_normalized.to_csv('TelecomX_Normalized.csv', index=False)

## Verify conversion

### Subtask:
Load the saved CSV file to ensure the conversion was successful and display the head of the new DataFrame.

**Reasoning**:
Load the newly created CSV file into a DataFrame and display its head to verify the conversion.

In [ ]:
df_from_csv = pd.read_csv('TelecomX_Normalized.csv')
display(df_from_csv.head())

## Summary:

### Data Analysis Key Findings

*   The JSON data from "TelecomX\_Data.json" was successfully loaded into a pandas DataFrame.
*   The nested structure of the JSON data was successfully flattened using `pd.json_normalize`, creating a DataFrame with columns representing the nested fields.
*   The normalized DataFrame was successfully saved to a CSV file named "TelecomX\_Normalized.csv" without including the DataFrame index.
*   The saved CSV file was successfully loaded back into a DataFrame, confirming the successful conversion process.

### Insights or Next Steps

*   The flattened CSV file is now ready for further data analysis or modeling tasks.
*   Consider exploring the data in the "TelecomX\_Normalized.csv" file to identify patterns or insights related to customer churn.

In [ ]:
df_normalized = pd.json_normalize(json_data.to_dict(orient='records'))
display(df_normalized.head())

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

In [ ]:
df_normalized.to_csv('TelecomX_Normalized.csv', index=False)

In [ ]:
df_from_csv = pd.read_csv('TelecomX_Normalized.csv')
display(df_from_csv.head())

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

In [2]:
value_counts = df_normalized['gender'].value_counts()
print(value_counts)

NameError: name 'df_normalized' is not defined

In [4]:
import pandas as pd
df_normalized = pd.json_normalize(json_data.to_dict(orient='records'))
value_counts = df_normalized['customer.gender'].value_counts()
print(value_counts)

NameError: name 'json_data' is not defined

In [5]:
json_data = pd.read_json('TelecomX_Data.json')

FileNotFoundError: File TelecomX_Data.json does not exist

In [6]:
value_counts()

NameError: name 'value_counts' is not defined

In [7]:
churn_counts = df_normalized['Churn'].value_counts()
print("Value counts for Churn column:")
print(churn_counts)

# Assuming 'No' represents active customers
active_customers = churn_counts.get('No', 0)
total_customers = churn_counts.sum()

if total_customers > 0:
    proportion_active = active_customers / total_customers
    print(f"\nProportion of active customers: {proportion_active:.2f}")
else:
    print("\nNo customer data available to calculate the proportion.")

NameError: name 'df_normalized' is not defined

In [8]:
import matplotlib.pyplot as plt
import seaborn as sns

# Select only numerical columns
numerical_df = df_normalized.select_dtypes(include=['number'])

# Calculate the correlation matrix
correlation_matrix = numerical_df.corr()

# Visualize the correlation matrix using a heatmap
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numerical Variables')
plt.show()

NameError: name 'df_normalized' is not defined

SyntaxError: invalid syntax (ipython-input-991839204.py, line 1)

To split the dataset into training and testing sets, we can use the `train_test_split` function from the `sklearn.model_selection` module. This is a crucial step in evaluating the performance of a machine learning model, as it allows us to train the model on a portion of the data and test it on unseen data.

In [10]:
from sklearn.model_selection import train_test_split

# Assuming 'df_normalized' is your DataFrame and 'Churn' is your target variable
# X will be the features (all columns except 'Churn')
# y will be the target variable ('Churn')
X = df_normalized.drop('Churn', axis=1)
y = df_normalized['Churn']

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training set shape (X_train, y_train):", X_train.shape, y_train.shape)
print("Testing set shape (X_test, y_test):", X_test.shape, y_test.shape)

NameError: name 'df_normalized' is not defined

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Assuming you have trained a model and made predictions on the test set
# Replace 'your_model' with your trained model and 'X_test' with your test features
# y_pred = your_model.predict(X_test)

# For demonstration purposes, let's create some dummy predictions
# In a real scenario, you would get predictions from your trained model
# Assuming y_test contains the true labels and y_pred contains the model's predictions
# Make sure y_test and y_pred are defined and have the same length

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, pos_label='Yes') # Assuming 'Yes' is the positive class
recall = recall_score(y_test, y_pred, pos_label='Yes')     # Assuming 'Yes' is the positive class
f1 = f1_score(y_test, y_pred, pos_label='Yes')         # Assuming 'Yes' is the positive class
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the evaluation metrics
print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-score: {f1:.2f}")

# Visualize the confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=['No Churn', 'Churn'], yticklabels=['No Churn', 'Churn'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()